In [1]:
import pandas as pd
import numpy as np

In [2]:
credits=pd.read_csv("./data/tmdb_5000_credits.csv")
movies=pd.read_csv("./data/tmdb_5000_movies.csv")

In [3]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
movies.isna().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [7]:
movies.dropna(subset=['overview'], inplace=True)

In [8]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [9]:
movies=movies.merge(credits,on="title")

In [10]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [11]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [12]:
movies=movies[['title','movie_id','genres','keywords','cast','crew','overview']]

In [13]:
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,John Carter,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [14]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import json
text=movies['genres'][0]
genre_list = json.loads(text)

print(genre_list)

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]

In [16]:
def genres_split(text):
    list= json.loads(text)
    gen=[]
    for i in list:
        gen.append(i['name'])
    return gen

In [17]:
movies['genres']=movies['genres'].apply(genres_split)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [18]:
movies['overview']=movies['overview'].apply(lambda x:x.replace(","," "))

In [19]:
movies['overview']=movies['overview'].apply(lambda x:x.replace("  "," "))

In [20]:
movies['overview'][0]

'In the 22nd century a paraplegic Marine is dispatched to the moon Pandora on a unique mission but becomes torn between following orders and protecting an alien civilization.'

In [21]:
movies['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [22]:
def keyword_split(text):
    list= json.loads(text)
    key=[]
    for i in list:
        key.append(i['name'])
    return key

In [23]:
movies['keywords']=movies['keywords'].apply(keyword_split)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Captain Barbossa long believed to be dead has ...
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter is a war-weary former military cap...

In [24]:
movies['cast'][0][:1000]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2'

In [25]:
def cast_split(text):
    list= json.loads(text)
    cast=[]
    for i in list:
        cast.append(i['name'])
    return cast

In [26]:
movies['cast']=movies['cast'].apply(cast_split)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Captain Barbossa long believed to be dead has ...
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter is a war-weary former military cap...

In [27]:
movies['crew'][0][:1000]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, '

In [28]:
def crew_split(text):
    list= json.loads(text)
    crew=[]
    for i in list:
        if i["job"]=="Director":
          crew.append(i['name'])
    return crew

In [29]:
movies['crew']=movies['crew'].apply(crew_split)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],Captain Barbossa long believed to be dead has ...
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],Following the death of District Attorney Harve...
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],John Carter is a war-weary former military cap...

In [30]:
def remove_space(l):
    for i in range(len(l)):
        l[i]=l[i].replace(" ",'')
        l[i]=l[i].lower()
    return l

In [31]:
movies['genres']=movies['genres'].apply(remove_space)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[action, adventure, fantasy, sciencefiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,"[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],Captain Barbossa long believed to be dead has ...
2,Spectre,206647,"[action, adventure, crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],Following the death of District Attorney Harve...
4,John Carter,49529,"[action, adventure, sciencefiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],John Carter is a war-weary former military cap...

In [32]:
movies['keywords']=movies['keywords'].apply(remove_space)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, ...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],Captain Barbossa long believed to be dead has ...
2,Spectre,206647,"[action, adventure, crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],Following the death of District Attorney Harve...
4,John Carter,49529,"[action, adventure, sciencefiction]","[basedonnovel, mars, medallion, spacetravel, p...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],John Carter is a war-weary former military cap...

In [33]:
movies['cast']=movies['cast'].apply(remove_space)
movies['crew']=movies['crew'].apply(remove_space)
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, ...","[samworthington, zoesaldana, sigourneyweaver, ...",[jamescameron],In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[johnnydepp, orlandobloom, keiraknightley, ste...",[goreverbinski],Captain Barbossa long believed to be dead has ...
2,Spectre,206647,"[action, adventure, crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[danielcraig, christophwaltz, léaseydoux, ralp...",[sammendes],A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretiden...","[christianbale, michaelcaine, garyoldman, anne...",[christophernolan],Following the death of District Attorney Harve...
4,John Carter,49529,"[action, adventure, sciencefiction]","[basedonnovel, mars, medallion, spacetravel, p...","[taylorkitsch, lynncollins, samanthamorton, wi...",[andrewstanton],John Carter is a war-weary former military cap...

In [34]:
movies['genres']=movies['genres'].apply(lambda x: " ".join(x))
movies['keywords']=movies['keywords'].apply(lambda x: " ".join(x))
movies['cast']=movies['cast'].apply(lambda x: " ".join(x))
movies['crew']=movies['crew'].apply(lambda x: " ".join(x))
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview
0,Avatar,19995,action adventure fantasy sciencefiction,cultureclash future spacewar spacecolony socie...,samworthington zoesaldana sigourneyweaver step...,jamescameron,In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,adventure fantasy action,ocean drugabuse exoticisland eastindiatradingc...,johnnydepp orlandobloom keiraknightley stellan...,goreverbinski,Captain Barbossa long believed to be dead has ...
2,Spectre,206647,action adventure crime,spy basedonnovel secretagent sequel mi6 britis...,danielcraig christophwaltz léaseydoux ralphfie...,sammendes,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,action crime drama thriller,dccomics crimefighter terrorist secretidentity...,christianbale michaelcaine garyoldman annehath...,christophernolan,Following the death of District Attorney Harve...
4,John Carter,49529,action adventure sciencefiction,basedonnovel mars medallion spacetravel prince...,taylorkitsch lynncollins samanthamorton willem...,andrewstanton,John Carter is a war-weary former military cap...

In [35]:
movies['description']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head()

,title,movie_id,genres,keywords,cast,crew,overview,description
0,Avatar,19995,action adventure fantasy sciencefiction,cultureclash future spacewar spacecolony socie...,samworthington zoesaldana sigourneyweaver step...,jamescameron,In the 22nd century a paraplegic Marine is dis...,In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,adventure fantasy action,ocean drugabuse exoticisland eastindiatradingc...,johnnydepp orlandobloom keiraknightley stellan...,goreverbinski,Captain Barbossa long believed to be dead has ...,Captain Barbossa long believed to be dead has ...
2,Spectre,206647,action adventure crime,spy basedonnovel secretagent sequel mi6 britis...,danielcraig christophwaltz léaseydoux ralphfie...,sammendes,A cryptic message from Bond’s past sends him o...,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,action crime drama thriller,dccomics crimefighter terrorist secretidentity...,christianbale michaelcaine garyoldman annehath...,christophernolan,Following the death of District Attorney Harve...,Following the death of District Attorney Harve...
4,John Carter,49529,action adventure sciencefiction,basedonnovel mars medallion spacetravel prince...,taylorkitsch lynncollins samanthamorton willem...,andrewstanton,John Carter is a war-weary former military cap...,John Carter is a war-weary former military cap...

In [36]:
new_movies=movies[['title','movie_id','description']]
new_movies.head()

,title,movie_id,description
0,Avatar,19995,In the 22nd century a paraplegic Marine is dis...
1,Pirates of the Caribbean: At World's End,285,Captain Barbossa long believed to be dead has ...
2,Spectre,206647,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...
4,John Carter,49529,John Carter is a war-weary former military cap...

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
vectorizer=CountVectorizer(max_features=5000,stop_words="english")
x=vectorizer.fit_transform(new_movies['description']).toarray()

In [39]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
distance_similarity = cosine_similarity(x)

In [43]:
def recommend1(name):
    movies_index = new_movies.loc[(movies["title"] == name)].index[0]
    dist_simi = list(enumerate(distance_similarity[movies_index]))

    dist_simi.sort(reverse=True, key=lambda x: x[1])

    return [i[0] for i in dist_simi[1:6]]

In [46]:
recommend1('')

SyntaxError: unterminated string literal (detected at line 1) (4148465886.py, line 1)

In [47]:
def recommand(name,n=5):
    index=new_movies[new_movies["title"]==name].index
    simi=cosine_similarity(x[index],x).flatten()
    indexed_simi = list(enumerate(simi, start=0)) # combine with index
    sorted_simi = sorted(indexed_simi, key=lambda x: x[1], reverse=True)
    l=[]
    
    for i in range(1,n+1):
        j = sorted_simi[i][0]
        l.append(new_movies['title'][j])
    return l

In [49]:
recommend1('Spectre')

[29, 11, 1344, 147, 3164]

In [50]:
recommand('Spectre')

['Skyfall',
 'Quantum of Solace',
 'Never Say Never Again',
 'Die Another Day',
 'Thunderball']

29    37724
Name: movie_id, dtype: int64

In [ ]:
l=[]
for i in new_movies['title']:
    l.append(recommand(i))
l

In [ ]:
new_movies

In [ ]:
new_movies['title'][972]

In [ ]:
recommand('The Host')

In [41]:
import pickle

In [63]:
pickle.dump(new_movies,open('movie_list.pkl','wb'))
pickle.dump(x,open('x.pkl','wb'))

In [42]:
pickle.dump(distance_similarity,open('distance_similarity.pkl','wb'))